# Production Docker Compose Configuration
# Use pre-built images from GitHub Container Registry
#
# Usage:
#   docker-compose -f docker-compose.prod.yml up -d
#
# Environment variables (set in .env or export):
#   - GIT_SHA: Git commit SHA (e.g., abc1234)
#   - IMAGE_TAG: Docker image tag (default: latest)
#   - POSTGRES_PASSWORD: Database password (REQUIRED in production)
#   - API_KEY: Application API key (REQUIRED in production)

services:
  postgres:
    image: postgres:15-alpine
    container_name: coffee-tracker-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-coffee}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # REQUIRED: Set in .env or environment
      - POSTGRES_DB=${POSTGRES_DB:-coffee_db}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-coffee}", "-d", "${POSTGRES_DB:-coffee_db}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

  redis:
    image: redis:7-alpine
    container_name: coffee-tracker-redis
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

  coffee-tracker:
    # Use pre-built image from GitHub Container Registry
    # Format: ghcr.io/USERNAME/REPO:TAG
    # Examples:
    #   - ghcr.io/dny1020/coffee-tracker:latest (main branch, latest)
    #   - ghcr.io/dny1020/coffee-tracker:main-abc1234 (specific commit)
    #   - ghcr.io/dny1020/coffee-tracker:develop (develop branch)
    image: ${DOCKER_IMAGE:-ghcr.io/dny1020/coffee-tracker:${IMAGE_TAG:-latest}}
    container_name: coffee-tracker
    pull_policy: always  # Always pull latest image on restart
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER:-coffee}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-coffee_db}
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
      - API_KEY=${API_KEY}  # REQUIRED: Set in .env or environment
      - FASTAPI_ENV=${FASTAPI_ENV:-production}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - TZ=${TZ:-UTC}
      - METRICS_PUBLIC=${METRICS_PUBLIC:-false}
      - SECURITY_HEADERS=${SECURITY_HEADERS:-true}
    
    networks:
      - traefik_net
      - internal
    
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.coffee-tracker.rule=Host(`${DOMAIN:-coffee.dommain.co}`)"
      - "traefik.http.routers.coffee-tracker.entrypoints=websecure"
      - "traefik.http.routers.coffee-tracker.tls=true"
      - "traefik.http.routers.coffee-tracker.tls.certresolver=myresolver"
      - "traefik.http.services.coffee-tracker.loadbalancer.server.port=8000"
    
    volumes:
      - ./data:/app/data
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 50s
    
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

volumes:
  redis_data:
  pg_data:

networks:
  traefik_net:
    external: true
  internal:
    driver: bridge
