# Prometheus Configuration for Coffee Tracker API
#
# This configuration scrapes metrics from the Coffee Tracker API
# Metrics are exposed at: http://coffee-tracker:8000/metrics
#
# IMPORTANT: 
# - If METRICS_PUBLIC=false in .env, update the Bearer token below with your API_KEY
# - If METRICS_PUBLIC=true in .env, you can remove the authorization section

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'coffee-tracker'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Coffee Tracker API metrics
  - job_name: 'coffee-tracker-api'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['coffee-tracker:8000']
        labels:
          service: 'coffee-tracker'
          app: 'fastapi'
          environment: 'production'
    # Authentication for metrics endpoint
    # OPTION 1: If METRICS_PUBLIC=false, uncomment and set your API_KEY
    # authorization:
    #   type: Bearer
    #   credentials: 'your-api-key-here'
    # 
    # OPTION 2: Set METRICS_PUBLIC=true in .env (recommended for internal networks)

  # PostgreSQL exporter (optional - requires postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #       labels:
  #         service: 'postgres'

  # Redis exporter (optional - requires redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #       labels:
  #         service: 'redis'

  # Node exporter (optional - for system metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         service: 'node-exporter'
